### ISSUE TITLE
Error: Unable to resolve module ./debugger-ui/debuggerWorker.

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#187]
Just curious why I get the following : 

```
Error: Unable to resolve module `./debugger-ui/debuggerWorker.cff11639` from ``: 

None of these files exist:
  * debugger-ui/debuggerWorker.cff11639(.native|.native.expo.ts|.expo.ts|.native.expo.tsx|.expo.tsx|.native.expo.js|.expo.js|.native.expo.jsx|.expo.jsx|.native.ts|.ts|.native.tsx|.tsx|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.wasm|.wasm)
  * debugger-ui/debuggerWorker.cff11639/index(.native|.native.expo.ts|.expo.ts|.native.expo.tsx|.expo.tsx|.native.expo.js|.expo.js|.native.expo.jsx|.expo.jsx|.native.ts|.ts|.native.tsx|.tsx|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.wasm|.wasm)
    at ModuleResolver.resolveDependency (/Users/pierrebresson/Documents/Git/nmf-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/pierrebresson/Documents/Git/nmf-app/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/pierrebresson/Documents/Git/nmf-app/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at /Users/pierrebresson/Documents/Git/nmf-app/node_modules/metro/src/lib/transformHelpers.js:267:42
    at /Users/pierrebresson/Documents/Git/nmf-app/node_modules/metro/src/Server.js:1096:37
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/pierrebresson/Documents/Git/nmf-app/node_modules/metro/src/Server.js:99:24)
    at _next (/Users/pierrebresson/Documents/Git/nmf-app/node_modules/metro/src/Server.js:119:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Unable to resolve module `./debugger-ui/debuggerWorker.cff11639` from ``: 
...
```

Seems like the app is working fine even with that, but would be good to know what's wrong.

<img width="1273" alt="Screenshot 2020-10-07 at 21 20 24" src="https://user-images.githubusercontent.com/8709134/95377597-118d3f80-08e3-11eb-9b67-3581372c943a.png">

**Comment by evayde** [comment]
Seems like it's a caching problem. Either remove chrome/device caches (or the app completely) or clean npm caches. Maybe also some stale sourcemaps, might need to clear the build folder.. This issue also occurs with react-native when debugging stuff gets stale.

**Comment by PierreBresson** [comment]
Thanks for the suggestion. I've tried removing app and `yarn cache clean` but I still have the warning
